### NUMPY

In [4]:
import numpy as np

In [5]:
data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print (data1, type(data1))
print (arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
data2 = [range(1,5), range(5,9)]
arr2 = np.array(data2)
print (data2, type(data2))
print (arr2, type(arr2))

[range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [8]:
list2 = arr2.tolist()
print (list2, type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [9]:
print (list(range(1,5)))

[1, 2, 3, 4]


In [15]:
print (arr1, type(arr1), id(arr1))
print (arr2, type(arr2), id(arr2))
print (arr1.dtype)
print (arr2.dtype)
print (arr1.shape, type(arr1.shape))
print (arr2.shape, type(arr2.shape))
print (arr1.ndim)
print (arr2.ndim)
print (arr1.size)

[1 2 3 4 5] <class 'numpy.ndarray'> 2110571150864
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 2110571525008
int32
int32
(5,) <class 'tuple'>
(2, 4) <class 'tuple'>
1
2
5


In [17]:
a = np.array([1 +9j, 3-25j, 5,7], dtype = complex)
a

array([1. +9.j, 3.-25.j, 5. +0.j, 7. +0.j])

In [26]:
a = np.array([[1,2,30],[10,15,24]])
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(np.sqrt(a))
print(np.std(a))

[[ 1  2 30]
 [10 15 24]]
30
1
82
[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 4.89897949]]
10.6874796945876


In [28]:
a = np.array([1,2,3,4,5])
b = np.array([7,8,9,4,2])
c = a*b
print (c)

[ 7 16 27 16 10]


In [29]:
a = np.array([[1,2,30],[10,15,24]])

for x in np.nditer(a):
    print(x, end =" ")

1 2 30 10 15 24 