In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5] # list
arr1 = np.array(data1)
print (data1, type(data1))
print (arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [11]:
b = np.array([[9, 8.5, 7, 0],[2, 4.3, 6, 3]])
print(b)

[[9.  8.5 7.  0. ]
 [2.  4.3 6.  3. ]]


In [12]:
a.ndim

1

In [13]:
b.shape

(2, 4)

In [14]:
a.dtype

dtype('int32')

In [15]:
a.itemsize

4

In [16]:
a.size

3

In [17]:
a.nbytes

12

In [18]:
b.itemsize


8

In [19]:
b.nbytes

64

##### Accessing/Changing specfic elements, rows, columns, etc.

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a[1, -2]

13

In [26]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
a[:, 2]

array([ 3, 10])

In [28]:
# Getting a little more fancy [startindex : endindex: stepsize]

In [49]:
a[0, 0:5:2]

array([5, 5, 5])

In [46]:
a[1, 5] = 20



print(a)

[[ 5  5  5  5  5  5  5]
 [ 5  5  5  5  5 20  5]]


In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
b[0,1,1]

4

In [53]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]]) 
print("Printing array:") 
print(a)
print("Iterating over the array:")
for x in np.nditer(a):
 print(x,end=" ")

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [56]:
a = np.array([[1,2,30],[10,15,4]]) 
print(np.sqrt(a))
print(np.std(a))


[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [57]:
a = 10 
b = 12
print("binary representation of a:",bin(a))
print("binary representation of b:",bin(b))
print("Bitwise-and of a and b: ",np.bitwise_and(a,b))
print("Bitwise-or of a and b: ",np.bitwise_or(a,b))


binary representation of a: 0b1010
binary representation of b: 0b1100
Bitwise-and of a and b:  8
Bitwise-or of a and b:  14


In [60]:
list1 = []

print("Enter the Elements: ")
for i in range(0,5):
    inputl = int(input())
    list1.append(inputl)

print(np.array(list1))

Enter the Elements: 
[5 2 4 8 7]


In [71]:
arr_zero = np.zeros(4)
print(arr_zero)
print()
arr_zero1 = np.zeros((3,4))
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [72]:
arr_rg = np.arange(4)
arr_rg

array([0, 1, 2, 3])

In [73]:
ar_dia = np.eye(3)

ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
arr_line = np.linspace(0, 10, num=5)
print(arr_line)

[ 0.   2.5  5.   7.5 10. ]


In [89]:
var = np.random.rand(5)

print(var) 

[0.51264008 0.88251974 0.66566839 0.05415778 0.56482502]


In [84]:
var1 = np.random.randn(2,5)

print(var1)

[[-1.28682414 -0.02702736 -1.21853697  0.94533123  0.68292935]
 [ 0.80212667 -1.25672375 -0.13938046  0.94475138 -0.03389371]]


In [90]:
rndm = np.random.randint(10,58,10)

print(rndm)

[52 10 29 49 27 48 40 18 16 11]


In [91]:

rnd = np.random.randn(4)
print (rnd)
print (rnd.mean())
print (rnd.std())
print (rnd.argmin()) 
print (rnd.argmax())

[-1.28400941  1.88617475 -0.07672127  0.54022762]
0.26641792359789057
1.1423827455669813
0
1


In [110]:
v = np.vstack((a, b))
print(v)
print()
c = np.concatenate((a, b), axis=0)
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
rnd = np.random.randn(4,2)
print (rnd)
print (rnd.sum(axis = 0)) 
print (rnd.sum(axis = 1)) 
print (np.cumsum(rnd))

[[-0.25002028 -0.33378449]
 [ 0.79691815 -1.2087338 ]
 [-1.79196714  0.30993351]
 [ 0.20541655  0.56267545]]
[-1.03965273 -0.66990933]
[-0.58380477 -0.41181565 -1.48203363  0.76809199]
[-0.25002028 -0.58380477  0.21311338 -0.99562041 -2.78758756 -2.47765405
 -2.2722375  -1.70956205]


In [94]:
rnd = np.random.randn(4, 2)
print (rnd)
print ((rnd > 0).sum()) 
print ((rnd > 0).any()) 

[[-0.44310883 -0.27696813]
 [-0.72489345 -0.65137383]
 [ 1.08382568 -0.73022303]
 [ 0.79068095  0.01989535]]
3
True


In [109]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Reshape the array permanently
arr.resize(2, 3)
#arr.reshape(3,2)
print(arr)

[[1 2 3]
 [4 5 6]]


In [105]:

f = arr.flatten()
print(f)


[1 2 3 4 5 6]


In [108]:
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([[5, 6], [7, 8]])
print(b)
h = np.hstack((a, b))
print(h)
c = np.concatenate((a, b), axis=1)
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [111]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.__lt__(4))
print(arr.__gt__(3))


[ True  True  True False False False]
[False False False  True  True  True]


In [113]:
tuple_1 = (1,2,3,4)
ar = np.asarray(tuple_1)
print(ar)

[1 2 3 4]


In [114]:

# To change the type
mx_1s = np.ones((3,4), dtype= int)
print(mx_1s)
mx_1s = np.ones((3,4), dtype= bool)
print(mx_1s)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [115]:
data1 = [1, 2, 3, 4, 5] # list
arr1 = np.array(data1) # 1-D array
print (arr1, type(arr1), arr1.dtype, arr1.shape)
print (arr1[0], arr1[-5])
print (arr1[4], arr1[-1])
print (arr1[2:], arr1[:3])

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
1 1
5 5
[3 4 5] [1 2 3]


In [116]:
print(np.gcd(100,750))
# Finding LCM
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

50
18
